test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------
    

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
  
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.2749e7b.name = "5.3.1 - packaging v1"

    